"""member1 core schema"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.CheckConstraint("name IN ('INVENTORY_MANAGER', 'WAREHOUSE_STAFF')", name="valid_role"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "warehouses",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_code", sa.String(length=32), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_code"),
    )
    op.create_table(
        "locations",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("short_code", sa.String(length=32), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["warehouse_id"], ["warehouses.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("warehouse_id", "short_code", name="uq_location_code"),
    )
    op.create_index(op.f("ix_locations_warehouse_id"), "locations", ["warehouse_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("unit_of_measure", sa.String(length=32), nullable=False),
        sa.Column(
            "initial_stock", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("initial_stock >= 0", name="nonnegative_initial_stock"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("login_id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failed_logins", sa.Integer(), server_default="0", nullable=False),
        sa.Column("locked_until", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["role"], ["roles.name"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("login_id"),
    )
    op.create_table(
        "password_resets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("otp_hash", sa.String(length=64), nullable=False),
        sa.Column("issued_at", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("reset_token_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("reset_token_hash"),
    )
    op.create_table(
        "reorder_rules",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("minimum_stock", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("reorder_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("minimum_stock >= 0", name="nonnegative_minimum_stock"),
        sa.CheckConstraint("reorder_quantity > 0", name="positive_reorder_quantity"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id"),
    )
    op.create_table(
        "stock_balances",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=18, scale=4), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="nonnegative_stock"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("product_id", "location_id"),
    )
    op.create_index(
        op.f("ix_stock_balances_location_id"), "stock_balances", ["location_id"], unique=False
    )
    op.create_table(
        "stock_ledger",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_type", sa.String(length=32), nullable=False),
        sa.Column("reference_id", sa.String(length=120), nullable=False),
        sa.Column("entry_key", sa.String(length=180), nullable=False),
        sa.Column("from_location_id", sa.Uuid(), nullable=True),
        sa.Column("to_location_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("before_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("after_quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "transaction_type IN ('INITIAL', 'RECEIPT', 'DELIVERY', 'TRANSFER', 'ADJUSTMENT')",
            name="valid_transaction_type",
        ),
        sa.CheckConstraint("after_quantity = before_quantity + quantity", name="ledger_arithmetic"),
        sa.CheckConstraint("before_quantity >= 0 AND after_quantity >= 0", name="valid_balances"),
        sa.CheckConstraint("quantity != 0", name="nonzero_movement"),
        sa.ForeignKeyConstraint(["from_location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["to_location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_key"),
    )
    op.create_index(
        op.f("ix_stock_ledger_location_id"), "stock_ledger", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_ledger_product_id"), "stock_ledger", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_ledger_reference_id"), "stock_ledger", ["reference_id"], unique=False
    )
    op.bulk_insert(
        sa.table("roles", sa.column("name", sa.String())),
        [
            {"name": "INVENTORY_MANAGER"},
            {"name": "WAREHOUSE_STAFF"},
        ],
    )
    op.execute("""CREATE FUNCTION reject_ledger_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'Stock ledger is append-only';
        END;
        $$ LANGUAGE plpgsql""")
    op.execute("""CREATE TRIGGER stock_ledger_immutable
        BEFORE UPDATE OR DELETE ON stock_ledger
        FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation()""")
    op.execute("""CREATE TRIGGER stock_ledger_no_truncate
        BEFORE TRUNCATE ON stock_ledger
        FOR EACH STATEMENT EXECUTE FUNCTION reject_ledger_mutation()""")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stock_ledger_reference_id"), table_name="stock_ledger")
    op.drop_index(op.f("ix_stock_ledger_product_id"), table_name="stock_ledger")
    op.drop_index(op.f("ix_stock_ledger_location_id"), table_name="stock_ledger")
    op.drop_table("stock_ledger")
    op.execute("DROP FUNCTION reject_ledger_mutation()")
    op.drop_index(op.f("ix_stock_balances_location_id"), table_name="stock_balances")
    op.drop_table("stock_balances")
    op.drop_table("reorder_rules")
    op.drop_table("password_resets")
    op.drop_table("users")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_locations_warehouse_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_table("warehouses")
    op.drop_table("roles")
    op.drop_table("categories")
    # ### end Alembic commands ###
